"""Command-line interface for generating mock Lyman-alpha forest FITS files."""

from __future__ import annotations

import argparse
from pathlib import Path

from .cosmology import LYA_REST_WAVELENGTH_ANGSTROM, build_cosmology
from .generator import generate_mock_catalog, generate_white_noise_catalog
from .geometry import assign_cartesian_coordinates
from .io import read_sightline_fits, write_sightline_fits
from .waves import build_plane_wave_set


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line argument parser for mock generation."""

    parser = argparse.ArgumentParser(description="Generate mock 3D Lyman-alpha forest fluctuations from plane-wave superpositions.")
    parser.add_argument("--input-fits", required=True, help="Input multi-extension FITS file containing sightlines.")
    parser.add_argument("--output-fits", required=True, help="Output FITS path for the generated mock sightlines.")
    parser.add_argument("--z-ref", required=True, type=float, help="Reference redshift used to define the relative line-of-sight coordinate.")
    parser.add_argument("--white-noise", action="store_true", help="Output pure uncorrelated Gaussian white noise (mean=0, sigma=noise-sigma) for every valid pixel, skipping plane-wave superposition.")
    parser.add_argument("--n-waves", type=int, default=None, help="Number of plane waves to superimpose (required unless --white-noise is set).")
    parser.add_argument("--k-min", type=float, default=None, help="Minimum wave-number magnitude in h/cMpc (required unless --white-noise is set).")
    parser.add_argument("--k-max", type=float, default=None, help="Maximum wave-number magnitude in h/cMpc (required unless --white-noise is set).")
    parser.add_argument("--noise-sigma", required=True, type=float, help="Global Gaussian noise sigma applied to every valid delta pixel.")
    parser.add_argument("--field-center-ra", type=float, default=None, help="Optional field-center RA in degrees. Defaults to the mean RA of the input sightlines.")
    parser.add_argument("--field-center-dec", type=float, default=None, help="Optional field-center Dec in degrees. Defaults to the mean Dec of the input sightlines.")
    parser.add_argument("--seed", type=int, default=0, help="Seed for both the plane-wave draw and the noise realization.")
    parser.add_argument("--h0", type=float, default=67.74, help="Fiducial Hubble constant in km/s/Mpc.")
    parser.add_argument("--om0", type=float, default=0.3089, help="Fiducial matter density parameter.")
    parser.add_argument("--tcmb0", type=float, default=2.7255, help="CMB temperature used by the fiducial cosmology.")
    parser.add_argument("--lambda-lya-rest", type=float, default=LYA_REST_WAVELENGTH_ANGSTROM, help="Rest-frame Lyman-alpha wavelength in Angstrom.")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite the output FITS if it already exists.")
    return parser


def _annotate_output_header(catalog, args: argparse.Namespace) -> None:
    """Store generation settings in the output primary FITS header."""

    header = catalog.primary_header
    header["MOCKLYA"] = (True, "Mock Lya forest generated by mock_lya_forest")
    header["INPUTBAS"] = (Path(args.input_fits).name, "Input FITS basename")
    header["ZREF"] = (float(args.z_ref), "Reference redshift for relative LOS coordinate")
    header["WNOISE"] = (bool(args.white_noise), "True if output is pure white noise")
    if not args.white_noise:
        header["NWAVES"] = (int(args.n_waves), "Number of superimposed plane waves")
        header["KMIN"] = (float(args.k_min), "Minimum k magnitude in h/cMpc")
        header["KMAX"] = (float(args.k_max), "Maximum k magnitude in h/cMpc")
    header["NSIGMA"] = (float(args.noise_sigma), "Global delta noise sigma")
    header["RNGSEED"] = (int(args.seed), "Seed used for waves and noise")
    header["COSMOH0"] = (float(args.h0), "Fiducial H0 in km/s/Mpc")
    header["COSMOOM0"] = (float(args.om0), "Fiducial Omega_m")
    header["TCMB0"] = (float(args.tcmb0), "Fiducial CMB temperature")
    header["LYALAM"] = (float(args.lambda_lya_rest), "Rest-frame Lya wavelength in Angstrom")
    if catalog.reference_redshift is not None:
        header["REFZGEN"] = (float(catalog.reference_redshift), "Stored reference redshift")
    if catalog.field_center_ra_deg is not None:
        header["FCRA"] = (float(catalog.field_center_ra_deg), "Field center RA in degrees")
    if catalog.field_center_dec_deg is not None:
        header["FCDEC"] = (float(catalog.field_center_dec_deg), "Field center Dec in degrees")
    header.add_history("Generated by mock_lya_forest from superposed real plane waves with global Gaussian noise.")


def main(argv: list[str] | None = None) -> None:
    """Run the mock-generation command-line workflow."""

    parser = build_parser()
    args = parser.parse_args(argv)

    if not args.white_noise and (args.n_waves is None or args.k_min is None or args.k_max is None):
        parser.error("--n-waves, --k-min, and --k-max are required unless --white-noise is set.")

    catalog = read_sightline_fits(args.input_fits)

    if args.white_noise:
        mock_catalog = generate_white_noise_catalog(
            catalog,
            noise_sigma=args.noise_sigma,
            seed=args.seed,
        )
    else:
        cosmology = build_cosmology(h0=args.h0, om0=args.om0, tcmb0=args.tcmb0)
        catalog = assign_cartesian_coordinates(
            catalog,
            cosmology=cosmology,
            z_ref=args.z_ref,
            field_center_ra_deg=args.field_center_ra,
            field_center_dec_deg=args.field_center_dec,
            lambda_lya_rest=args.lambda_lya_rest,
        )
        wave_set = build_plane_wave_set(
            n_waves=args.n_waves,
            k_min=args.k_min,
            k_max=args.k_max,
            seed=args.seed,
        )
        mock_catalog = generate_mock_catalog(
            catalog,
            wave_set=wave_set,
            noise_sigma=args.noise_sigma,
            seed=args.seed,
        )
    _annotate_output_header(mock_catalog, args)
    write_sightline_fits(args.output_fits, mock_catalog, overwrite=args.overwrite)


if __name__ == "__main__":
    main()